### ISSUE TITLE
List view for groups

### ISSUE THREAD

**Issue by pauldipietro** [aaronfeng/punchcard-io-feature-requests#5]
To Aaron: you know we already spoke about the project after the Philly.rb meeting tonight and I'm definitely interested in helping out in any way I can. I'll probably just put some small UI requests in as I see them for the time being, since I don't have access to code.

One thing I've noticed missing which is probably modestly simple to implement would be a list view alongside the larger images that appear. That way one would be able to fit more content and potentially sort it by different attributes (title/perhaps the number of meetings attended, etc.).

I'm always willing to do mockups or something along those lines, if desired!

**Comment by aaronfeng** [comment]
For sure.  The site def need some UI love. Drop me an email, we can go from there. Thx for "Punching In" tonight!
